name: cargo-mutants

on: [push]

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        name: Install cargo-mutants using install-action
        with:
          tool: cargo-mutants
      - name: Run mutant tests
        run: cargo mutants -vV --in-place
      - name: Archive results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutants-out
          path: mutants.out

